### ISSUE TITLE
Update to 2015.03 release

### ISSUE THREAD

**Issue by zostay** [szabgab/perl6-travis-ci#1]
Would it be possible to get this updated to 2015.03? There have been several significant changes to Perl 6 in the past 3 months that are causing my Travis CI tests to fail at the moment.

**Comment by timo** [comment]
actually, i'd appreciate having a bit in the readme that mentions the other travis CI example module in the ecosystem that uses rakudobrew to get an up-to-date rakudo every time

**Comment by szabgab** [comment]
@timo you might want to send a pull request to include the link to the other CI example

**Comment by szabgab** [comment]
README is now recommending the other Travis CI integration. The one that actually works.
@zostay please switch to that one.
